DROP TABLE LineaFactura IF EXISTS;
DROP TABLE ReciboInmueble IF EXISTS;
DROP TABLE FACTURA IF EXISTS;
DROP TABLE NotaInformativa IF EXISTS;
DROP TABLE INMUEBLES IF EXISTS;
DROP TABLE COMUNIDADES IF EXISTS;
DROP TABLE Concepto IF EXISTS;
DROP TABLE PROPIETARIOS IF EXISTS;

CREATE TABLE PROPIETARIOS (
       NIF CHAR(10) NOT NULL
     , NOMBRE CHAR(40)
     , DIRECCION CHAR(40)
     , POBLACION CHAR(40)
     , TELEFONO CHAR(10)
     , OBSERVACIONES CHAR(10)
     , FECHA_ALTA DATE
     , Entidad CHAR(20)
     , NumeroCuenta INTEGER
     , PRIMARY KEY (NIF)
);

CREATE TABLE Concepto (
       ClaveConcepto CHAR(5) NOT NULL
     , Descripcion CHAR(30)
     , PRIMARY KEY (ClaveConcepto)
);

CREATE TABLE COMUNIDADES (
       NOMBRE CHAR(10) NOT NULL
     , CALLE CHAR(40)
     , MAX_RECIBOS_PENDIENTES INTEGER
     , ESTADO CHAR(40)
     , PROPIETARIO CHAR(10)
     , PRIMARY KEY (NOMBRE)
);

CREATE TABLE INMUEBLES (
       ID_INMUEBLE INTEGER NOT NULL PRIMARY KEY
     , ESCALERA CHAR(10)
     , PISO CHAR(10)
     , PUERTA CHAR(10)
     , PORCENTAJE FLOAT
     , NOMBRE CHAR(10)
     , NIF CHAR(10) NOT NULL
);

CREATE TABLE NotaInformativa (
       FechaCalculo DATE
     , ImporteNota DOUBLE
     , ID_Nota INTEGER NOT NULL
     , NOMBRE CHAR(10) NOT NULL
     , PRIMARY KEY (ID_Nota)
);

CREATE TABLE FACTURA (
       NumFactura INTEGER NOT NULL
     , FechaFactura DATE
     , NOMBRE CHAR(10) NOT NULL
     , ID_Nota INTEGER 
     , PRIMARY KEY (NumFactura)
);

CREATE TABLE ReciboInmueble (
       FechaPago DATE
     , Importe DOUBLE
     , ID_INMUEBLE INTEGER NOT NULL
     , ID_Recibo INTEGER NOT NULL
     , ID_Nota INTEGER NOT NULL
     , PRIMARY KEY (ID_Recibo)
);

CREATE TABLE LineaFactura (
       ImporteLinea DOUBLE
     , Observacion CHAR(40)
     , NumFactura INTEGER NOT NULL
     , ID_Linea INTEGER NOT NULL
     , ClaveConcepto CHAR(5)
     , PRIMARY KEY (ID_Linea)
);

ALTER TABLE COMUNIDADES
  ADD CONSTRAINT FK_COMUNIDADES_2
      FOREIGN KEY (NOMBRE)
      REFERENCES COMUNIDADES (NOMBRE);

ALTER TABLE COMUNIDADES
  ADD CONSTRAINT FK_COMUNIDADES_3
      FOREIGN KEY (PROPIETARIO)
      REFERENCES PROPIETARIOS (NIF);

ALTER TABLE INMUEBLES
  ADD CONSTRAINT FK_INMUEBLES_1
      FOREIGN KEY (NIF)
      REFERENCES PROPIETARIOS (NIF);

ALTER TABLE INMUEBLES
  ADD CONSTRAINT FK_INMUEBLES_2
      FOREIGN KEY (NOMBRE)
      REFERENCES COMUNIDADES (NOMBRE);

ALTER TABLE NotaInformativa
  ADD CONSTRAINT FK_NotaInformativa_4
      FOREIGN KEY (NOMBRE)
      REFERENCES COMUNIDADES (NOMBRE);

ALTER TABLE FACTURA
  ADD CONSTRAINT FK_FACTURA_1
      FOREIGN KEY (NOMBRE)
      REFERENCES COMUNIDADES (NOMBRE);

ALTER TABLE FACTURA
  ADD CONSTRAINT FK_FACTURA_2
      FOREIGN KEY (ID_Nota)
      REFERENCES NotaInformativa (ID_Nota);

ALTER TABLE ReciboInmueble
  ADD CONSTRAINT FK_ReciboInmueble_1
      FOREIGN KEY (ID_INMUEBLE)
      REFERENCES INMUEBLES (ID_INMUEBLE);

ALTER TABLE ReciboInmueble
  ADD CONSTRAINT FK_ReciboInmueble_2
      FOREIGN KEY (ID_Nota)
      REFERENCES NotaInformativa (ID_Nota);

ALTER TABLE LineaFactura
  ADD CONSTRAINT FK_LineaFactura_1
      FOREIGN KEY (NumFactura)
      REFERENCES FACTURA (NumFactura)
   ON DELETE CASCADE;

ALTER TABLE LineaFactura
  ADD CONSTRAINT FK_LineaFactura_2
      FOREIGN KEY (ClaveConcepto)
      REFERENCES Concepto (ClaveConcepto);

