package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

//import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Comunidad generated by hbm2java
 */
public class Comunidad /*implements java.io.Serializable*/ {

	private String nombre;
	private String calle;
	private Integer maxRecibosPendientes;
	private String estado;
	private Propietario presidente;
	private Set<Factura> facturas = new HashSet<Factura>(0);
	private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);
	private Set<NotaInformativa> notaInformativas = new HashSet<NotaInformativa>(
			0);

	public Comunidad() {
	}

	public Comunidad(String nombre) {
		this.nombre = nombre;
	}

	public Comunidad(String nombre, String calle, Integer maxRecibosPendientes,
			String estado, Propietario presidente, Set<Factura> facturas,
			Set<Inmueble> inmuebles, Set<NotaInformativa> notaInformativas) {
		this.nombre = nombre;
		this.calle = calle;
		this.maxRecibosPendientes = maxRecibosPendientes;
		this.estado = estado;
		this.presidente = presidente;
		this.facturas = facturas;
		this.inmuebles = inmuebles;
		this.notaInformativas = notaInformativas;
	}

	public Comunidad(String nombre, String calle,
			Integer maxRecibosPendientes, String estado,
			Propietario presidente, Set<Factura> facturas,
			Set<NotaInformativa> notaInformativas) {
		this.nombre = nombre;
		this.calle = calle;
		this.maxRecibosPendientes = maxRecibosPendientes;
		this.estado = estado;
		this.presidente = presidente;
		this.facturas = facturas;
		this.notaInformativas = notaInformativas;
	}
	
	public Comunidad(String nombre, String calle,
			Integer maxRecibosPendientes, String estado,
			Propietario presidente) {
		this.nombre = nombre;
		this.calle = calle;
		this.maxRecibosPendientes = maxRecibosPendientes;
		this.estado = estado;
		this.presidente = presidente;
	}

	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getMaxRecibosPendientes() {
		return this.maxRecibosPendientes;
	}

	public void setMaxRecibosPendientes(Integer maxRecibosPendientes) {
		this.maxRecibosPendientes = maxRecibosPendientes;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Propietario getPresidente() {
		return this.presidente;
	}

	public void setPresidente(Propietario presidente) {
		this.presidente = presidente;
	}

	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

	public void addInmueble(Inmueble i) {
		this.inmuebles.add(i);
	}
	
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Set<NotaInformativa> getNotaInformativas() {
		return this.notaInformativas;
	}

	public void setNotaInformativas(Set<NotaInformativa> notaInformativas) {
		this.notaInformativas = notaInformativas;
	}
	
	@Override
	public boolean equals(Object arg0) {
		if(arg0 instanceof Comunidad){
			Comunidad c=(Comunidad) arg0;
			return this.nombre.equals(c.getNombre());
		}
		return false;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.nombre;
	}
	
}
