package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
@SuppressWarnings("serial")
public class Concepto implements java.io.Serializable {

	private String claveconcepto;
	private String descripcion;
	private Set<LineaFactura> lineaFacturas = new HashSet<LineaFactura>(0);

	public Concepto() {
	}

	public Concepto(String claveconcepto) {
		this.claveconcepto = claveconcepto;
	}

	public Concepto(String claveconcepto, String descripcion,
			Set<LineaFactura> lineaFacturas) {
		this.claveconcepto = claveconcepto;
		this.descripcion = descripcion;
		this.lineaFacturas = lineaFacturas;
	}
	
	public Concepto(String claveconcepto, String descripcion) {
		this.claveconcepto = claveconcepto;
		this.descripcion = descripcion;
	}
	
	public String getClaveconcepto() {
		return this.claveconcepto;
	}

	public void setClaveconcepto(String claveconcepto) {
		this.claveconcepto = claveconcepto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<LineaFactura> getLineaFacturas() {
		return this.lineaFacturas;
	}

	public void setLineaFacturas(Set<LineaFactura> lineaFacturas) {
		this.lineaFacturas = lineaFacturas;
	}
	
	@Override
	public boolean equals(Object arg0) {
		if(arg0 instanceof Concepto){
			Concepto c=(Concepto) arg0;
			return this.claveconcepto.equals(c.getClaveconcepto());
		}
		return false;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.claveconcepto;
	}

}
