package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
@SuppressWarnings("serial")
public class Inmueble implements java.io.Serializable {

	private int idInmueble;
	private Comunidad comunidad;
	private Propietario propietario;
	private String escalera;
	private String piso;
	private String puerta;
	private Double porcentaje;
	private Set<ReciboInmueble> reciboInmuebles = new HashSet<ReciboInmueble>(0);

	public Inmueble() {
	}

	public Inmueble(int idInmueble, Propietario propietario) {
		this.idInmueble = idInmueble;
		this.propietario = propietario;
	}

	public Inmueble(int idInmueble, Comunidad comunidad,
			Propietario propietario, String escalera, String piso,
			String puerta, Double porcentaje,
			Set<ReciboInmueble> reciboInmuebles) {
		this.idInmueble = idInmueble;
		this.comunidad = comunidad;
		this.propietario = propietario;
		this.escalera = escalera;
		this.piso = piso;
		this.puerta = puerta;
		this.porcentaje = porcentaje;
		this.reciboInmuebles = reciboInmuebles;
	}

	public Inmueble(int idInmueble,  String escalera, String piso,
			String puerta, Double porcentaje, Propietario propietario, 
			Comunidad comunidad
			) {
		this.idInmueble = idInmueble;
		this.comunidad = comunidad;
		this.propietario = propietario;
		this.escalera = escalera;
		this.piso = piso;
		this.puerta = puerta;
		this.porcentaje = porcentaje;
	}
	
	public Inmueble(String escalera, String piso,
			String puerta, Double porcentaje, Propietario propietario, 
			Comunidad comunidad
			) {
		this.comunidad = comunidad;
		this.propietario = propietario;
		this.escalera = escalera;
		this.piso = piso;
		this.puerta = puerta;
		this.porcentaje = porcentaje;
		//comunidad.addInmueble(this);
	}
	
	public int getIdInmueble() {
		return this.idInmueble;
	}

	public void setIdInmueble(int idInmueble) {
		this.idInmueble = idInmueble;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public Propietario getPropietario() {
		return this.propietario;
	}

	public void setPropietario(Propietario propietario) {
		this.propietario = propietario;
	}

	public String getEscalera() {
		return this.escalera;
	}

	public void setEscalera(String escalera) {
		this.escalera = escalera;
	}

	public String getPiso() {
		return this.piso;
	}

	public void setPiso(String piso) {
		this.piso = piso;
	}

	public String getPuerta() {
		return this.puerta;
	}

	public void setPuerta(String puerta) {
		this.puerta = puerta;
	}

	public Double getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Set<ReciboInmueble> getReciboInmuebles() {
		return this.reciboInmuebles;
	}

	public void setReciboInmuebles(Set<ReciboInmueble> reciboInmuebles) {
		this.reciboInmuebles = reciboInmuebles;
	}
	
	
	@Override
	public boolean equals(Object arg0) {
		if(arg0 instanceof Inmueble){
			Inmueble i=(Inmueble) arg0;
			return this.idInmueble == i.getIdInmueble();
		}
		return false;
	}

}
