package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

/**
 * LineaFactura generated by hbm2java
 */
@SuppressWarnings("serial")
public class LineaFactura implements java.io.Serializable {

	private int idLinea;
	private Factura factura;
	private Concepto concepto;
	private Double importelinea;
	private String observacion;

	public LineaFactura() {
	}

	public LineaFactura(int idLinea, Factura factura) {
		this.idLinea = idLinea;
		this.factura = factura;
	}

	public LineaFactura(int idLinea, Factura factura, Concepto concepto,
			Double importelinea, String observacion) {
		this.idLinea = idLinea;
		this.factura = factura;
		this.concepto = concepto;
		this.importelinea = importelinea;
		this.observacion = observacion;
	}

	public LineaFactura(Factura factura, Concepto concepto,
			Double importelinea, String observacion) {
		this.factura = factura;
		this.concepto = concepto;
		this.importelinea = importelinea;
		this.observacion = observacion;
	}
	
	public int getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(int idLinea) {
		this.idLinea = idLinea;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
//		factura.getLineaFacturas().add(this);
		
	}

	public Concepto getConcepto() {
		return this.concepto;
	}

	public void setConcepto(Concepto concepto) {
		this.concepto = concepto;
	}

	public Double getImportelinea() {
		return this.importelinea;
	}

	public void setImportelinea(Double importelinea) {
		this.importelinea = importelinea;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
