package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NotaInformativa generated by hbm2java
 */
@SuppressWarnings("serial")
public class NotaInformativa implements java.io.Serializable {

	private int idNota;
	private Comunidad comunidad;
	private Date fechacalculo;
	private Set<Factura> facturas = new HashSet<Factura>(0);
	private Double importenota;
	private Set<ReciboInmueble> reciboInmuebles = new HashSet<ReciboInmueble>(0);

	public NotaInformativa() {
	}
	
	public NotaInformativa(int idNota, Comunidad comunidad) {
		this.idNota = idNota;
		this.comunidad = comunidad;
	}

	public NotaInformativa(int idNota, Comunidad comunidad, Date fechacalculo,
			Double importenota, Set<Factura> facturas,
			Set<ReciboInmueble> reciboInmuebles) {
		this.idNota = idNota;
		this.comunidad = comunidad;
		this.fechacalculo = fechacalculo;
		this.importenota = importenota;
		this.facturas = facturas;
		this.reciboInmuebles = reciboInmuebles;
	}

	public NotaInformativa(Comunidad comunidad, Date fechacalculo,
			Double importenota) {
		this.comunidad = comunidad;
		this.fechacalculo = fechacalculo;
		this.importenota = importenota;
	}
	
	public int getIdNota() {
		return this.idNota;
	}

	public void setIdNota(int idNota) {
		this.idNota = idNota;
	}

	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public Set<ReciboInmueble> getReciboInmuebles() {
		return this.reciboInmuebles;
	}

	public void setReciboInmuebles(Set<ReciboInmueble> reciboInmuebles) {
		this.reciboInmuebles = reciboInmuebles;
	}

	public Date getFechacalculo() {
		return this.fechacalculo;
	}

	public void setFechacalculo(Date fechacalculo) {
		this.fechacalculo = fechacalculo;
	}

	public Double getImportenota() {
		return this.importenota;
	}

	public void setImportenota(Double importenota) {
		this.importenota = importenota;
	}

	public String toString() {
		// TODO Auto-generated method stub
		return ""+this.idNota;
	}
}
