package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Propietario generated by hbm2java
 */
@SuppressWarnings("serial")
public class Propietario implements java.io.Serializable {

	private String nif;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telefono;
	private String observaciones;
	private Date fechaAlta;
	private String entidad;
	private Integer numerocuenta;
	private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

	public Propietario() {
	}

	public Propietario(String nif) {
		this.nif = nif;
	}

	public Propietario(String nif, String nombre, String direccion,
			String poblacion, String telefono, String observaciones,
			Date fechaAlta, String entidad, Integer numerocuenta,
			Set<Inmueble> inmuebles) {
		this.nif = nif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.observaciones = observaciones;
		this.fechaAlta = fechaAlta;
		this.entidad = entidad;
		this.numerocuenta = numerocuenta;
		this.inmuebles = inmuebles;
	}


	public Propietario(String nif, String nombre, String direccion,
			String poblacion, String telefono, String observaciones,
			Date fechaAlta, String entidad, Integer numerocuenta) {
		this.nif = nif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.observaciones = observaciones;
		this.fechaAlta = fechaAlta;
		this.entidad = entidad;
		this.numerocuenta = numerocuenta;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	public Integer getNumerocuenta() {
		return this.numerocuenta;
	}

	public void setNumerocuenta(Integer numerocuenta) {
		this.numerocuenta = numerocuenta;
	}

	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.nombre;
	}

	@Override
	public boolean equals(Object arg0) {
		if(arg0 instanceof Propietario){
			Propietario p=(Propietario) arg0;
			return this.nif.equals(p.getNif());
		//	return this.idPropietario==p.getIdPropietario();
		}
		return false;
	}
	
}
