package dominio;

// Generated 06-may-2013 23:18:13 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReciboInmueble generated by hbm2java
 */
@SuppressWarnings("serial")
public class ReciboInmueble implements java.io.Serializable {

	private Integer idRecibo;
	private Inmueble inmueble;
	private Date fechapago;
	private Double importe;
	private NotaInformativa notaInformativa;

	public ReciboInmueble() {
	}

	public ReciboInmueble(int idRecibo, NotaInformativa notaInformativa,
			Inmueble inmueble) {
		this.idRecibo = idRecibo;
		this.notaInformativa = notaInformativa;
		this.inmueble = inmueble;
	}

	public ReciboInmueble(int idRecibo, NotaInformativa notaInformativa,
			Inmueble inmueble, Date fechapago, Double importe) {
		this.idRecibo = idRecibo;
		this.notaInformativa = notaInformativa;
		this.inmueble = inmueble;
		this.fechapago = fechapago;
		this.importe = importe;
	}
	
	public ReciboInmueble(Inmueble inmueble, Double importe, NotaInformativa notaInformativa) {
		this.inmueble = inmueble;
		this.importe = importe;
		this.notaInformativa = notaInformativa;
	}
	
	public ReciboInmueble(int idRecibo, Inmueble inmueble) {
		this.idRecibo = idRecibo;
		this.inmueble = inmueble;
	}
	public Integer getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo(Integer idRecibo) {
		this.idRecibo = idRecibo;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public Date getFechapago() {
		return this.fechapago;
	}

	public void setFechapago(Date fechapago) {
		this.fechapago = fechapago;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	public NotaInformativa getNotaInformativa() {
		return this.notaInformativa;
	}

	public void setNotaInformativa(NotaInformativa notaInformativa) {
		this.notaInformativa = notaInformativa;
	}

}
